name: Nginx DockerHub & S3 Push

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  S3_BUCKET_NAME: my-github-actions-bucket

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull Nginx Image from DockerHub
        run: docker pull nginx

      - name: Tag Nginx Image DockerHub Usernme
        run: docker tag v1.0 mynginx:latest $DOCKERHUB_USERNAME/mynginx:latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Push Nginx Image to DockerHub
        run: docker push $DOCKERHUB_USERNAME/mynginx:latest
        
      
      - name: Configure AWS credntials
        run: |
           aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws s3 ls
    

        
        




     
