name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Test Repo workflow
        run: |
          curl -H "Accept: application/vnd.github+json" -H "Authorization: token secrets.MY_SECRET" --request POST --data '{"ref": "main"}' https://api.github.com/repos/nagoorbasha7869/myownrepository/actions/workflows/build.yml/dispatches
