name: Hello World
on: [push]

jobs:
  print_hello_world:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello World
      run: echo "Hello, world!"
      
  my_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Call my_workflow
        uses: ./.github/workflows/build.yml
