name: hello-world
on: workflow_dispatch
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Call my_workflow
        uses: ./.github/workflows/build.yml
