name: Trigger Hello World

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Hello World
        uses: nagoorbasha7869/newrepo@main
        with:
          token: ${{ secrets.MY_ACCESS_TOKEN }}
          repository: nagoorbasha7869/newrepo
          workflow: hello-world.yml


