name: Trigger Hello  World
on:
  push:
    branches:
      - main
jobs:
  trigger_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: nagoorbasha7869/myownrepository
          event-type: hello_world
