name: Trigger Workflow

on:
  push:
    branches:
      - main

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        uses: nagoorbasha7869/myownrepository@main
        with:
          token: ${{ secrets.MY_ACCESS_TOKEN}}
          repository: nagoorbasha7869/myownrepository
          event-type: trigger-workflow
