name: Dispatch Workflow
on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'The owner and name of the repository to dispatch the workflow in.'
        required: true
        default: 'nagoorbasha7869/myownrepository'
      event-type:
        description: 'The type of event to trigger in the target repository.'
        required: true
        default: 'hello_world'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in another repository
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.MY_ACCESS_TOKEN }}
          repository: ${{ github.event.inputs.repository }}
          event-type: ${{ github.event.inputs.event-type }}
          client-payload: '{}'

