name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List repository contents
        run: ls -R

      - name: Download GitHub Action
        uses: nagoorbasha7869/myownrepository@main
        with:
          my_input: 'hello world'
